Introduce the `deprecated` settings
The deprecated set works as a black list.

For now we deprecated lttng 2.7, 2.8 since UST fails to build on modern
(18.04 ubuntu).

  ../include/lttng/ust-tid.h:38:21: error: static declaration of ‘gettid’ follows non-static declaration
   static inline pid_t gettid(void)
                       ^~~~~~
  In file included from /usr/include/unistd.h:1170,
                   from ring_buffer_backend.c:22:
  /usr/include/x86_64-linux-gnu/bits/unistd_ext.h:34:16: note: previous declaration of ‘gettid’ was here
   extern __pid_t gettid (void) __THROW;

Lttng-tools 2.9 also fail for now. I am discussing with the maintainer
if we can go forward with a fix.

Signed-off-by: Jonathan Rajotte <jonathan.rajotte-julien@efficios.com>